### ISSUE TITLE
Logotipo

### ISSUE THREAD

**Issue by fernandounger** [luas10c/poketruco-nextjs#2]
### Fiz essas logo baseada no Pokémon para o jogo Pokétruco.
![PokeTruco](https://user-images.githubusercontent.com/87918106/182035431-a897e4ad-9522-4007-bc0d-d06550a57865.png)
![Captura_de_tela_2022-07-31_131249-removebg-preview (1)](https://user-images.githubusercontent.com/87918106/182035495-97edc64e-9a56-4505-97e2-04f43697b6a6.png)

**Comment by luas10c** [comment]
Muitooooooooooooooooooooooooooooooooo bom
